name: noise_protocol
version: 0.1.2
homepage: https://github.com/bcattaneo/dart-noise-protocol
description:
  A Dart implementation of Noise protocol, which can be used for securing communications (E2EE,
  etc.).

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  collection: ^1.14.0
  cryptography: ^1.0.0
  # cryptography: ^2.0.5
  meta: ^1.1.0
  # kms: ^0.4.0
  typed_data: ^1.1.0
  convert: ^2.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0

dependency_overrides:
  meta: 1.6.0
